### ISSUE TITLE
Cache not found

### ISSUE THREAD

**Issue by vjose1903** [c-hive/gha-npm-cache#15]
I'm using windows-latest in the workflow, and I'm trying to cache the dependencies so that the process runs faster. and I only get this message:

Run c-hive/gha-npm-cache@v1
"C:\Program Files\Git\usr\bin\uname.exe"
MSYS_NT-10.0-20348
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\node\16.15.1\x64\npm.cmd config get cache"
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
C:\npm\cache
Cache keys: MSYS_NT-10.0-20348-npm-cache-1458c27d3e2bedec3251db8741195aca, MSYS_NT-10.0-20348-npm-cache-
Cache not found.

but at the end it gives me the message that the cache was saved:

Post job cleanup.
C:\Windows\System32\tar.exe -z -cf cache.tgz -P -C D:/a/novac-system/novac-system --files-from manifest.txt
Cache saved successfully.

I need help

**Comment by thisismydesign** [comment]
Share your workflow file please

**Comment by vjose1903** [comment]
yes there is:

name: Build and Deploy

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: c-hive/gha-npm-cache@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci --force

      - name: Build Novac App
        id: build-novac-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron:windows64

**Comment by thisismydesign** [comment]
Closing, this functionality is now part of [`actions/setup-node`](https://github.com/actions/setup-node).
