### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by JoeDuncko** [c-hive/gha-npm-cache#4]
Monorepo support would be super awesome.

**Comment by thisismydesign** [comment]
What isn't covered for that in practice? I thought the cache folder would be the same.

**Comment by JoeDuncko** [comment]
I get the following error. In retrospect, I should have posted this as my issue. Sorry about that!

![image](https://user-images.githubusercontent.com/6749768/116014673-63d64980-a604-11eb-90e3-26fecf60db3c.png)

**Comment by thisismydesign** [comment]
Ah, gotcha. An optional input for `package-lock.json` should be easy enough to implement.

Used here:
https://github.com/c-hive/gha-npm-cache/blob/b02613765d4fa6f3900755e3e1aa4a84bf07100a/src/restore.js#L37

Example for input handling:
https://github.com/c-hive/gha-remove-artifacts/blob/a90e7c756ec7fd07fd143c1f36b5e0c20a0fd66b/index.js#L25

No promises from my side at the moment but happy to take PRs.

**Comment by thisismydesign** [comment]
Resolved via v1.1.0 based on https://github.com/c-hive/gha-yarn-cache/pull/15. Thanks to @viktigpetterr.

Bumped the v1 tag so you can use this right away with your existing workflow.
